name: Create and Publish Docker Image for SalesForce DS
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
jobs:
  build:
    permissions:
      id-token: write # need this for OIDC
      contents: read
      actions: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}

      - name: Build, tag and push image
        env:
          ECR_REGISTRY: ghcr.io
          IMAGE_TAG: ${{ env.PROJECT_VERSION }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          docker login -u AtlasInsideCorp -p ${{ secrets.GITHUB_TOKEN }} $ECR_REGISTRY
          docker build -t ghcr.io/atlasinsidecorp/${{inputs.image_name}}:${{inputs.environment}} .
          docker image push ghcr.io/atlasinsidecorp/${{inputs.image_name}}:${{inputs.environment}}
