name: Create and Publish Docker Image for SalesForce DS
on:
  pull_request:
    types:
      - closed
    branches: [ master ]
jobs:
  docker-sf:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # need this for OIDC
      contents: read
      actions: write
      packages: write
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: utmstack.azurecr.io
          username: github
          password: ${{secrets.REGISTRY_KEY}}

      - name: Build Image
        run: docker build -t utmstack.azurecr.io/sforceds:v9 .

      - name: Push Image
        run: docker push utmstack.azurecr.io/sforceds:v9
