name: Create and Publish Docker Image for SalesForce DS
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
jobs:
  build:
    permissions:
      id-token: write # need this for OIDC
      contents: read
      actions: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: c3s4rfred
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: /home/runner/work/sforceds/sforceds/
          push: true
          tags: ghcr.io/c3s4rfred/${{inputs.image_name}}:${{inputs.environment}}_${{ env.TAG }},ghcr.io/c3s4rfred/${{inputs.image_name}}:${{inputs.environment}}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{inputs.environment}}_${{ env.TAG }}"
